"""
ZORA AI - Labs Router
=====================
Protected endpoints for ZORA Code, Design, Image, Vid, and Research.
"""

import json

from fastapi import APIRouter, Depends, HTTPException, Request, status
from pydantic import BaseModel, Field, field_validator
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.database import get_db
from app.middleware.auth_middleware import get_current_user
from app.models.user import User
from app.services.gemini import generate_gemini_response, generate_image
from app.services.nvidia import generate_nvidia_response
from app.utils.prompt_builder import load_prompt_file
from app.utils.rate_limit import limiter, user_or_ip_key

router = APIRouter()

DESIGN_TYPES = {"brief", "copy", "concept"}
IMAGE_STYLES = {
    "photorealistic",
    "anime",
    "digital art",
    "oil painting",
    "watercolor",
    "sketch",
    "3D render",
    "pixel art",
    "cinematic",
}
LANGUAGES = {
    "Python",
    "JavaScript",
    "TypeScript",
    "HTML/CSS",
    "SQL",
    "Bash",
    "Java",
    "C++",
    "Go",
    "Rust",
}
RESEARCH_DEPTHS = {"quick", "standard", "deep"}


def api_success(data: dict, message: str) -> dict:
    return {
        "status": "success",
        "success": True,
        "data": data,
        "message": message,
    }


def parse_code_result(raw_text: str, language: str) -> dict:
    stripped = (raw_text or "").strip()
    code = stripped
    explanation = "Generated by Zora Code."

    if "```" in stripped:
        parts = stripped.split("```")
        if len(parts) >= 3:
            fenced = parts[1]
            code_lines = fenced.splitlines()
            if code_lines:
                if code_lines[0].strip().lower() == language.lower():
                    code = "\n".join(code_lines[1:]).strip()
                else:
                    code = "\n".join(code_lines[1:] if len(code_lines) > 1 else code_lines).strip()
            explanation = parts[2].replace("Explanation:", "").strip() or explanation
    elif "Explanation:" in stripped:
        code, explanation = stripped.split("Explanation:", 1)
        code = code.strip()
        explanation = explanation.strip()

    return {
        "code": code,
        "explanation": explanation,
        "language": language,
    }


def parse_design_result(raw_text: str) -> dict:
    sections = {
        "concept": "",
        "colors": "",
        "typography": "",
        "tone": "",
        "copy": "",
    }
    current_key = None

    for line in (raw_text or "").splitlines():
        stripped = line.strip()
        if not stripped:
            continue

        matched = False
        for key in sections:
            title = key.capitalize()
            if stripped.lower().startswith(f"{title.lower()}:"):
                sections[key] = stripped.split(":", 1)[1].strip()
                current_key = key
                matched = True
                break
        if not matched and current_key:
            sections[current_key] = f"{sections[current_key]} {stripped}".strip()

    for key, fallback in {
        "concept": "Refined visual direction generated by Zora Design.",
        "colors": "Cyan, deep black, and cool neutral support tones.",
        "typography": "Inter for interface text with a bold display accent.",
        "tone": "Confident, modern, and clear.",
        "copy": "A polished draft is ready for refinement.",
    }.items():
        if not sections[key]:
            sections[key] = fallback

    return sections


def build_vid_response() -> dict:
    return {"enabled": False, "message": "Coming Soon"}


def parse_research_result(raw_text: str, depth: str) -> dict:
    lines = [line.strip("- ").strip() for line in (raw_text or "").splitlines() if line.strip()]
    summary = lines[0] if lines else f"Zora Research {depth} summary is ready."
    sections = [
        {"title": f"Finding {index + 1}", "content": line}
        for index, line in enumerate(lines[1:4])
    ] or [{"title": "Overview", "content": "Research synthesis will appear here."}]
    return {
        "summary": summary,
        "sections": sections,
        "sources": [],
        "further_reading": lines[4:7],
    }


def build_lab_messages(prompt_text: str, user_payload: str) -> list[dict]:
    return [
        {"role": "system", "content": prompt_text},
        {"role": "user", "content": user_payload},
    ]


class CodeLabRequest(BaseModel):
    prompt: str = Field(..., min_length=1)
    language: str

    @field_validator("prompt")
    @classmethod
    def clean_prompt(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Prompt is required")
        return value

    @field_validator("language")
    @classmethod
    def validate_language(cls, value: str) -> str:
        if value not in LANGUAGES:
            raise ValueError("Unsupported language")
        return value


class DesignLabRequest(BaseModel):
    prompt: str = Field(..., min_length=1)
    type: str

    @field_validator("prompt")
    @classmethod
    def clean_prompt(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Prompt is required")
        return value

    @field_validator("type")
    @classmethod
    def validate_type(cls, value: str) -> str:
        normalized = value.strip().lower()
        if normalized not in DESIGN_TYPES:
            raise ValueError("Unsupported design type")
        return normalized


class ImageLabRequest(BaseModel):
    prompt: str = Field(..., min_length=1)
    style: str

    @field_validator("prompt")
    @classmethod
    def clean_prompt(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Prompt is required")
        return value

    @field_validator("style")
    @classmethod
    def validate_style(cls, value: str) -> str:
        if value not in IMAGE_STYLES:
            raise ValueError("Unsupported image style")
        return value


class VidLabRequest(BaseModel):
    prompt: str | None = None


class ResearchLabRequest(BaseModel):
    query: str = Field(..., min_length=1)
    depth: str = "standard"

    @field_validator("query")
    @classmethod
    def clean_query(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("Query is required")
        return value

    @field_validator("depth")
    @classmethod
    def validate_depth(cls, value: str) -> str:
        normalized = value.strip().lower()
        if normalized not in RESEARCH_DEPTHS:
            raise ValueError("Unsupported research depth")
        return normalized


@router.post("/code")
@limiter.limit("20/minute", key_func=user_or_ip_key)
async def zora_code(
    http_request: Request,
    request: CodeLabRequest,
    current_user: User = Depends(get_current_user),
):
    try:
        prompt_text = load_prompt_file("labs/code.txt")
        raw_text = await generate_nvidia_response(
            "qwen",
            build_lab_messages(
                prompt_text,
                f"Language: {request.language}\nTask: {request.prompt}",
            ),
        )
        return api_success(
            parse_code_result(raw_text, request.language),
            "Zora Code generated successfully",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate code: {exc}") from exc


@router.post("/design")
@limiter.limit("20/minute", key_func=user_or_ip_key)
async def zora_design(
    http_request: Request,
    request: DesignLabRequest,
    current_user: User = Depends(get_current_user),
):
    try:
        prompt_text = load_prompt_file("labs/design.txt")
        raw_text = await generate_nvidia_response(
            "minimax",
            build_lab_messages(
                prompt_text,
                f"Type: {request.type}\nBrief: {request.prompt}",
            ),
        )
        return api_success(
            parse_design_result(raw_text),
            "Zora Design generated successfully",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate design output: {exc}") from exc


@router.post("/image")
@limiter.limit("20/minute", key_func=user_or_ip_key)
async def zora_image(
    http_request: Request,
    request: ImageLabRequest,
    current_user: User = Depends(get_current_user),
):
    try:
        prompt_text = load_prompt_file("labs/image.txt")
        image_result = await generate_image(request.prompt, request.style, prompt_text)
        return api_success(image_result, "Zora Image generated successfully")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate image: {exc}") from exc


@router.post("/vid")
@limiter.limit("20/minute", key_func=user_or_ip_key)
async def zora_vid(
    http_request: Request,
    request: VidLabRequest,
    current_user: User = Depends(get_current_user),
):
    return api_success(build_vid_response(), "Zora Vid is coming soon")


@router.post("/research")
@limiter.limit("20/minute", key_func=user_or_ip_key)
async def zora_research(
    http_request: Request,
    request: ResearchLabRequest,
    current_user: User = Depends(get_current_user),
):
    try:
        prompt_text = load_prompt_file("labs/research.txt")
        raw_text = await generate_gemini_response(
            build_lab_messages(
                prompt_text,
                f"Depth: {request.depth}\nQuery: {request.query}",
            )
        )
        return api_success(
            parse_research_result(raw_text, request.depth),
            "Zora Research generated successfully",
        )
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Failed to generate research output: {exc}") from exc
